# Generated by Django 4.1.1 on 2022-10-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='categories_done',
            field=models.ManyToManyField(blank=True, to='quiz.category'),
        ),
    ]
